name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Debug Secrets (DO NOT PRINT PASSWORDS)   
        run: |
          if [[ -z "${{ secrets.DOCKER_NAME }}" ]]; then 
            echo "ERROR: DOCKER_NAME is empty"; exit 1; 
          else 
            echo "DOCKER_NAME is set"; 
          fi

          if [[ -z "${{ secrets.DOCKER_PASS }}" ]]; then 
            echo "ERROR: DOCKER_PASS is empty"; exit 1; 
          else 
            echo "DOCKER_PASS is set"; 
          fi

      - name: Login to Docker Hub
        run: |
          echo "Logging into Docker Hub..."
          echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_NAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t integrationninjas/nodejs-app .

      - name: Publish Image to Docker Hub
        run: docker push integrationninjas/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    env:
      DOCKER_NAME: ${{ secrets.DOCKER_NAME }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      MONGO_PASS: ${{ secrets.MONGO_PASS }}

    steps:
      - name: Debug Environment Variables on Self-Hosted Runner
        run: |
          echo "Checking if DOCKER_NAME is set: $DOCKER_NAME"
          echo "Checking if DOCKER_PASS is set: ${#DOCKER_PASS} characters long"

      - name: Login to Docker Hub
        run: |
          if [[ -z "$DOCKER_NAME" || -z "$DOCKER_PASS" ]]; then
            echo "ERROR: DOCKER_NAME or DOCKER_PASS is empty on self-hosted runner"
            exit 1
          fi
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_NAME" --password-stdin

      - name: Pull image from Docker Hub
        run: docker pull integrationninjas/nodejs-app:latest

      - name: Delete old container (if exists)
        run: |
          docker stop nodejs-app-container || true
          docker rm nodejs-app-container || true

      - name: Run Docker Container
        run: |
          docker run -d -p 4000:4000 \
            --name nodejs-app-container \
            -e MONGO_PASSWORD="$MONGO_PASS" \
            integrationninjas/nodejs-app:latest
