name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Debug Secrets (DO NOT PRINT PASSWORDS)
        run: |
          echo "Checking Secrets..."
          if [ -z "${{ secrets.DOCKER_NAME }}" ]; then 
            echo "ERROR: DOCKER_NAME is empty"; exit 1; 
          else 
            echo "DOCKER_NAME is set"; 
          fi
          if [ -z "${{ secrets.DOCKER_PASS }}" ]; then 
            echo "ERROR: DOCKER_PASS is empty"; exit 1; 
          else 
            echo "DOCKER_PASS is set"; 
          fi

      - name: Logout to Clear Credentials
        run: docker logout || true

      - name: Login to Docker Hub (Use PAT)
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_NAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t engrdawoodisrar/nodejs-app:latest .

      - name: Publish Image to Docker Hub
        run: docker push engrdawoodisrar/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Logout to Ensure Fresh Login
        run: docker logout || true

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_NAME }}" --password-stdin

      - name: Pull Image from Docker Hub
        run: docker pull engrdawoodisrar/nodejs-app:latest

      - name: Stop and Remove Old Container (if exists)
        run: |
          docker stop nodejs-app-container || true
          docker rm nodejs-app-container || true

      - name: Run Docker Container
        run: |
          docker run -d -p 4000:4000 \
            --name nodejs-app-container \
            -e MONGO_PASSWORD="${{ secrets.MONGO_PASS }}" \
            engrdawoodisrar/nodejs-app:latest
