jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Debug Secrets (DO NOT PRINT PASSWORDS)
        run: |
          if [[ -z "${{ secrets.DOCKER_NAME }}" ]]; then 
            echo "ERROR: DOCKER_NAME is empty"; exit 1; 
          else 
            echo "DOCKER_NAME is set"; 
          fi

          if [[ -z "${{ secrets.DOCKER_PASS }}" ]]; then 
            echo "ERROR: DOCKER_PASS is empty"; exit 1; 
          else 
            echo "DOCKER_PASS is set";     
          fi

  deploy:
    needs: build
    runs-on: self-hosted
    env:
      DOCKER_NAME: ${{ secrets.DOCKER_NAME }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      MONGO_PASS: ${{ secrets.MONGO_PASS }}

    steps:
      - name: Debug Environment Variables on Self-Hosted Runner
        run: env | grep DOCKER

      - name: Login to Docker Hub
        run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_NAME" --password-stdin

      - name: Pull image from Docker Hub
        run: docker pull integrationninjas/nodejs-app:latest

      - name: Delete old container (if exists)
        run: |
          docker stop nodejs-app-container || true
          docker rm nodejs-app-container || true

      - name: Run Docker Container
        run: |
          docker run -d -p 4000:4000 \
            --name nodejs-app-container \
            -e MONGO_PASSWORD="$MONGO_PASS" \
            integrationninjas/nodejs-app:latest
