name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  - name: Debug Secrets and Environment Variables
    run: |
    echo "DOCKER_NAME: '${{ secrets.DOCKER_NAME }}'"
    echo "DOCKER_PASS: '${{ secrets.DOCKER_PASS }}'"
    echo "MONGO_PASS: '${{ secrets.MONGO_PASS }}'"

    if [[ -z "${{ secrets.DOCKER_NAME }}" ]]; then 
      echo "❌ ERROR: DOCKER_NAME is empty"; exit 1;
    else 
      echo "✅ DOCKER_NAME is set";
    fi

    if [[ -z "${{ secrets.DOCKER_PASS }}" ]]; then 
      echo "❌ ERROR: DOCKER_PASS is empty"; exit 1;
    else 
      echo "✅ DOCKER_PASS is set";
    fi

    if [[ -z "${{ secrets.MONGO_PASS }}" ]]; then 
      echo "❌ ERROR: MONGO_PASS is empty"; exit 1;
    else 
      echo "✅ MONGO_PASS is set";
    fi
