name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Debug Secrets
        run: |
          echo "DOCKER_NAME=${{ secrets.DOCKER_NAME }}"
          echo "DOCKER_PASS length: ${#DOCKER_PASS}"
        env: 
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}  

      - name: Login to Docker Hub
        run: |
          if [[ -z "${{ secrets.DOCKER_NAME }}" || -z "${{ secrets.DOCKER_PASS }}" ]]; then
            echo "ERROR: DOCKER_NAME or DOCKER_PASS is not set"
            exit 1
          fi
          echo "Logging into Docker Hub..."
          echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_NAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t integrationninjas/nodejs-app .

      - name: Publish Image to Docker Hub
        run: docker push integrationninjas/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull integrationninjas/nodejs-app:latest

      - name: Delete old container (if exists)
        run: |
          docker stop nodejs-app-container || true
          docker rm nodejs-app-container || true

      - name: Run Docker Container
        run: |
          docker run -d -p 4000:4000 \
            --name nodejs-app-container \
            -e MONGO_PASSWORD="${{ secrets.MONGO_PASS }}" \
            integrationninjas/nodejs-app:latest
